### PR TITLE
Poppy CDN

### PR DESCRIPTION
**Pull request by mdarby**

### CODE REVIEW

**Comment by geemus** [comment]
Test fail seems unrelated. Otherwise seems reasonable. I'll leave it be as long as it is WIP, but just let me know when it needs review and I'll dig in. Thanks!

**Comment by mdarby** [comment]
Thanks @geemus. I have a super-super short deadline on this. Other side of the API is still being developed and will be ready to roll tonight. I will work to update and I would _greatly appreciate_ a fast merge when I ping this thread.

**Comment by geemus** [comment]
Got it. I'll do what I can. Probably should be able to review tomorrow if it is ready.

**Comment by mdarby** [comment]
Thanks! The changes will be small. I'd say this represents 97% of the PR at this point. Mainly just API changes to deal with.

**Comment by mdarby** [comment]
@geemus this is ready to merge. Tests are in a separate repo and will be merged when fog-rackspace goes live:

```
..........

Finished in 0.12987 seconds (files took 0.76262 seconds to load)
10 examples, 0 failures
```

**Comment by geemus** [comment]
Cool, thanks!

**Comment by geemus** [comment]
Does this need a release also and/or when?

**Comment by mdarby** [comment]
Thanks @geemus! This Poppy CDN support is an on going feature but it will be available to select customers -- as such I've directed them to update their gemfiles to this ref.

**Pull request merged**
