### PR TITLE
edit

### PR DESCRIPTION
**Pull request by ltmr2016**

### CODE REVIEW

**Comment by h0lyalg0rithm** [comment]
@plribeiro3000 too much spam due to github's Hacktoberfest

**Comment by plribeiro3000** [comment]
This looks to be a spam account. Closing

**Comment by plribeiro3000** [comment]
@h0lyalg0rithm Yeah. Kind of bad. They should use their own test repos for this.

**Comment by h0lyalg0rithm** [comment]
@plribeiro3000 yeah definitely

**Comment by geemus** [comment]
Thanks for cleaning up.

**Pull request closed without merging**
