### PR TITLE
added requests files for linode image and linode disk api calls

### PR DESCRIPTION
**Pull request by displague**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@displague Is this PR ready to be merged?

@geemus Tho to bug in here?

**Comment by displague** [comment]
I believe we've changed some of the returned values since I created this PR. I'll follow up.

**Comment by geemus** [comment]
@plribeiro3000 probably just me I fear.

@displague cool, thanks!

**Comment by plribeiro3000** [comment]
@displague LMK when this is ready to be reviewed again please.

**Comment by displague** [comment]
I'm hoping to make the unmocked Linode tests pass.  They don't currently.

I'm also going to have to add https://www.linode.com/api/image/image.update which was added since this PR started.

**Comment by plribeiro3000** [comment]
@displague Whats the status here? Do you need some help?

**Comment by displague** [comment]
I haven't been able to give this any time, and honeatly I have been hinging my work on this against a Linode internal PR. The code here should be ready to go, I didn't get all the tests passing but they are better than they were before this PR.  The test for the new features pass.

**Comment by plribeiro3000** [comment]
@displague Thanks and sorry for the delay here.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
