### PR TITLE
Move digitalocean to gem

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**
Removed everything related to digitalocean. 
Depends on 
https://github.com/fog/fog-digitalocean/pull/9
https://github.com/fog/fog-core/pull/195

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@h0lyalg0rithm It seems both PR's you linked have minor details to be fixed. Once it gets fixed we need to release `fog-digitalocean` and give release access to @geemus and myself.
Let me know when you do one of those steps.

**Comment by h0lyalg0rithm** [comment]
@plribeiro3000 I have fixed the issues you mentioned.I will release the fog-digitalocean gem in a bit

**Comment by geemus** [comment]
Oops, guess I may be slightly premature. Please do release that when you have a chance, thanks!

**Comment by h0lyalg0rithm** [comment]
Thanks @geemus I just released the gem

**Comment by h0lyalg0rithm** [comment]
@geemus I added you as the gem owner

**Comment by geemus** [comment]
Great, thanks!

**Comment by h0lyalg0rithm** [comment]
:heavy_plus_sign: @plribeiro3000 Just added you to the owners.

**Comment by plribeiro3000** [comment]
@h0lyalg0rithm Awesome. Thanks!

**Comment by plribeiro3000** [comment]
@h0lyalg0rithm Before we move and extract the original code from fog we need to make the compliant with our latest standards. Some of them are just to make sure it is following the same convention as others but some are related to issues we had in the past.

Could you check [this wiki page](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch) and change the code to follow it?

Thanks!

**Pull request merged**
