### PR TITLE
 CloudAtCost apis

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**
Cloudatcost has documented their apis at [docs](https://github.com/cloudatcost/api)

### CODE REVIEW

**Comment by geemus** [comment]
@h0lyalg0rithm Rather than bringing this into the main repo, would you be up for getting it setup as an independent repo and gem which we can just require? I think that will keep things simpler in terms of maintenance. Thanks!

**Comment by h0lyalg0rithm** [comment]
Not a problem, will move it a different repo.

**Comment by geemus** [comment]
Thanks. Just let me know when you are ready and we can move it to `fog/fog-cloudatcost` or something similar to that.

**Comment by h0lyalg0rithm** [comment]
@geemus How do i transfer the repo to fog organization ??

**Comment by geemus** [comment]
@h0lyalg0rithm the easiest way is to just transfer to me, then I can transfer it into the org and make sure you have admin rights. Thanks!

**Comment by h0lyalg0rithm** [comment]
@geemus I have made you the owner of the repo.

**Comment by geemus** [comment]
@h0lyalg0rithm thanks, I'll try to finish the transition shortly.

**Comment by geemus** [comment]
Actually, I just looked and the transfer had expired (apparently they only last about a day). Could you try again and I'll make sure to be quicker this time? Thanks!

**Comment by h0lyalg0rithm** [comment]
No probs,Will do it again

**Comment by geemus** [comment]
Should be done, just let me know if I missed anything or you have questions. Thanks!

**Comment by h0lyalg0rithm** [comment]
Thanks :+1:

**Pull request closed without merging**
