### PR TITLE
Do not Merge yet! Remove google

### PR DESCRIPTION
**Pull request by plribeiro3000**
Once fog/fog-google#5 is merged and the gem is published this will be g2g.

cc/ @icco @erjohnso @ihmccreery

### CODE REVIEW

**Comment by ihmccreery** [comment]
Okay, I've released a fog-google [gem](https://rubygems.org/gems/fog-google), and I've done some spot testing.  It looks like if I install a `gem build` of your branch, then I get the following behavior:

```
> require 'fog'
=> true
> connection = Fog::Compute.new({ provider: 'google', ... })
=> # huge blob of stuff
> server = connection.servers.bootstrap
=> # looks good
> server.destroy
> # also looks good
```

I'm willing to call this good.  However, I also have

```
> require 'fog-google'
LoadError: cannot load such file -- fog-google
```

Is this desired behavior for now?  I think eventually we'd like these provider gems to stand on their own, but I see similar behavior with other `fog-provider` gems.

**Comment by ihmccreery** [comment]
Wait.  When I do a `bundle install` in the `fog` repository, it's installing `fog-google 0.0.1`, which doesn't have the binary.  Any ideas?

**Comment by plribeiro3000** [comment]
You should be doing `fog/google`, not `fog-google`.

I will force the suage og version `0.0.2` to fix this issue. Give me a minute. =)

**Comment by ihmccreery** [comment]
Lol.  New around here.

Version forcing actually isn't necessary, since no one should see 0.0.1 except me, since I yanked it, but maybe good anyway.  (I fixed my issue with `bundle update`.)

**Comment by plribeiro3000** [comment]
Good to know its fixed for you then.

Beware `gem yank`. It is as bad as it seems. :skull:

**Comment by ihmccreery** [comment]
Note taken.

**Comment by ihmccreery** [comment]
So we're good to go on this, yes?

**Comment by plribeiro3000** [comment]
Yep. The build just passed. =)

You are good to go on with `fog-google` now!

**Comment by ihmccreery** [comment]
:herb: :tulip: :sunflower: :herb:

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
