### PR TITLE
Fixes #3084: Implement OpenStack Identity V3 API

### LINKED ISSUE #3084: Domain support in Identity v3
With the Identity v2.0 API marked as deprecated in Icehouse (alltho reverted after release), cloud providers are starting to require using the v3 API to authenticate.

This is needed to support domains, to achieve full multi-tenancy in public clouds.

The v2.0 API seems to be scheduled for removal in the Kilo release next year.

Please look into supporting v3 and domains.

Documentation for the v3 API:
* http://api.openstack.org/api-ref-identity-v3.html

Aviator support for v3 API:
* https://github.com/aviator/aviator/blob/master/lib/aviator/openstack/identity/requests/v3/public/create_token.rb

### PR DESCRIPTION
**Pull request by dhague**
Fog::Identity::OpenStack.new() will return either a V2 API object or a V3 API object depending on the auth URL
Fog::OpenStack::Core.authenticate switches on the auth URL to call the V2 or V3 authentication API

Old implementation Fog::Identity::OpenStack is now at Fog::Identity::OpenStack::V2, and the related models & requests have been moved from <folder>/identity to <folder>/identity_v2.

Tests for the v3 API have been done as VCR recordings against a Keystone (Juno) installation.

### CODE REVIEW

**Comment by TerryHowe** [comment]
I'd like to look at it closer, but giving it a quick look, looks great!

**Comment by dhague** [comment]
This is getting very frustrating - the build is still failing with Ruby 1.8.7, but not for any reason to do with this pull request as far as I can see.
I run Ubuntu 14.04.2 and I can't get RVM to install 1.8.7 so it's pretty much impossible for me to test that version locally - apologies for all the micro-commits to get this far.

**Comment by geemus** [comment]
@dhague sorry to hear about the issues, I'll try to dig in and help out soon (it's been a super busy week).

**Comment by dhague** [comment]
Seems like a conflict between minitest and RSpec. Working on it now...

**Comment by geemus** [comment]
@dhague ah, yeah I could see how that might be an issue. I didn't realize there were some of both here (at some point a lot of things have become a bit of a blur with so many moving parts). Just let me know if you have questions or anything I can further help with. Thanks!

**Comment by dhague** [comment]
Just about fixed it now - thanks

**Comment by dhague** [comment]
Just let me know if you'd prefer me to rebase & squash and submit this as one commit instead of nine commits.

**Comment by geemus** [comment]
Awesome, I commend you on sticking to it through that painful bit. I'm fine with more commits, but you are welcome to rebase & squash also. I'm getting toward my EOD, so will probably try to review/merge in whatever form it is tomorrow.

**Comment by dhague** [comment]
Rebased and squashed - hopefully a bit easier to review.

**Comment by dhague** [comment]
:-(

**Comment by TerryHowe** [comment]
Sort of the merge issue, lgtm!

**Comment by geemus** [comment]
Yeah, in general seems good, looks like some of the squash went bad though, tests appear to have an undefined constant issue now :(

@dhague sorry this turned out to be so painful, hopefully we are nearly done with it at least.

**Pull request closed without merging**
