### PR TITLE
Fixes #3084: Implement OpenStack Identity V3 API

### LINKED ISSUE #3084: Domain support in Identity v3
With the Identity v2.0 API marked as deprecated in Icehouse (alltho reverted after release), cloud providers are starting to require using the v3 API to authenticate.

This is needed to support domains, to achieve full multi-tenancy in public clouds.

The v2.0 API seems to be scheduled for removal in the Kilo release next year.

Please look into supporting v3 and domains.

Documentation for the v3 API:
* http://api.openstack.org/api-ref-identity-v3.html

Aviator support for v3 API:
* https://github.com/aviator/aviator/blob/master/lib/aviator/openstack/identity/requests/v3/public/create_token.rb

### PR DESCRIPTION
**Pull request by dhague**
Fog::Identity::OpenStack.new() will return either a V2 API object or a V3 API object depending on the auth URL
Fog::OpenStack::Core.authenticate switches on the auth URL to call the V2 or V3 authentication API

Trying with a new PR using freshly rebased & squashed code

### CODE REVIEW

**Comment by dhague** [comment]
This is crazy. I have run this locally now:
$ ruby --version;rvm --version;bundle --version;gem --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Bundler version 1.9.6
2.4.6

$  git fetch origin +refs/pull/3560/merge:
$  git checkout -qf FETCH_HEAD
$  export BUNDLE_GEMFILE=$PWD/gemfiles/Gemfile-ruby-1.8.7
$  rm $PWD/gemfiles/Gemfile-ruby-1.8.7.lock
$  bundle install --jobs=3 --retry=3
$  bundle exec rake travis 

Everything runs fine. My git log is as follows:
commit 8cb397d9b326c9de1d1d31719daae07d8ef9aee6
Merge: bc71bed 2f3c6ac
Author: Darren Hague <d.hague@sap.com>
Date:   Fri May 8 09:48:38 2015 +0000

    Merge 2f3c6ac3b432023e6ab5077f4f03c98b183ba528 into bc71bedbdc19d9af3fe12a6873411eaa22a9f657

commit 2f3c6ac3b432023e6ab5077f4f03c98b183ba528
Author: Darren Hague <d.hague@sap.com>
Date:   Wed Apr 29 12:27:16 2015 +0100

    Fixes #3084: Implement OpenStack Identity V3 API
    
    Fog::Identity::OpenStack.new() will return either a V2 API object or a V3 API object depending on the auth U
    Fog::OpenStack::Core.authenticate switches on the auth URL to call the V2 or V3 authentication API

commit bc71bedbdc19d9af3fe12a6873411eaa22a9f657
Author: geemus <geemus@gmail.com>
Date:   Thu May 7 13:47:31 2015 -0500

    rework tasks to better integrate github release creation/tagging


Could somebody else please try running the sequence above to see whether it's me or Travis which is crazy?

**Comment by TerryHowe** [comment]
every g2g @dhague ?  Looks it.  If so, get it while it is green.

**Comment by dhague** [comment]
Unfortunately not - there was no build triggered from that last commit, which was just a forced push of a squashed commit. The original code still triggered a red build by Travis. I'd really appreciate you fetching the PR commits and trying a build yourself, if you have time.

**Comment by dhague** [comment]
OK, so I finally made some progress - partly by realizing I could trigger Travis builds from my own Github repo, and partly by just reverting to a last-known-good commit and working from there.
I will close this PR, and the next PR should be good to go.

**Comment by plribeiro3000** [comment]
@dhague Could you do a force push here again to see if if triggers another build?

I just tried to manually retrigger it from Travis but it tried the same commit again. =s

**Comment by plribeiro3000** [comment]
Awesome. Thanks @dhague !

**Comment by jrafanie** [comment]
Other than adding new commits, rewriting a commit and force pushing, you can also just close and reopen the PR with no other changes and it should trigger Travis.

**Pull request closed without merging**
