### PR TITLE
Add instance_types support to oVirt provider

### PR DESCRIPTION
**Pull request by bagasse**
Add instance_types support to oVirt provider. Depends on https://github.com/abenari/rbovirt/pull/117 merged today, but not released ATM.

### CODE REVIEW

**Comment by geemus** [comment]
@bagasse sounds good, could you just ping us when that has been released so we can follow up? Thanks!

**Comment by bagasse** [comment]
@geemus, the rbovirt was released today.

**Comment by geemus** [comment]
@bagasse cool, do we need anything else here, or is this good to go now? (sorry it's been long enough I forget the specific context).

**Comment by bagasse** [comment]
@geemus, this is good for me.

**Comment by bagasse** [comment]
Rebased and gem spec file updated to update dev dependency on rbovirt 0.1.3

**Comment by geemus** [comment]
Great, thanks!

**Comment by bagasse** [comment]
@geemus, thanks for your time, there is any new gem release planned, and if yes do you have any time frame ? Thank you.

**Comment by geemus** [comment]
@bagasse hey, sorry, last week kind of got away from me. I'll try to get it out some time this week though.

**Comment by geemus** [comment]
Sorry for delays, 1.39.0 should now be available, thanks!

**Comment by bagasse** [comment]
Thank you !

**Pull request merged**
