### PR TITLE
[Fog 2.0] Remove 1.8.7 support

### PR DESCRIPTION
**Pull request by tokengeek**
This is the official commit to drop Ruby 1.8.7 support from fog.

This is a backwards incompatible change (for hopefully obvious reasons)
so will be part of the next MAJOR fog release `v2.0`

Ruby 1.8.7 is no longer supported by the language developers.

Anyone needing to stay on Ruby 1.8.7 such as users of LTS distros should
remain on the `v1.x` series of fog.

### CODE REVIEW

**Comment by calebthompson** [comment]
1.9.3 is also EOL. https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by geemus** [comment]
Yeah. I think we should drop it, but we will probably wait for a major version bump to do it.

**Comment by calebthompson** [comment]
Sorry, maybe I misunderstand. Isn't this a branch for a major version bump?

**Comment by geemus** [comment]
Oh, right, sorry. My brain was still thinking about the travis related matrix changes...

**Comment by calebthompson** [comment]
Right. And _that_ PR was to this branch :D

**Comment by geemus** [comment]
AH. I totally missed that context I guess.

**Comment by tokengeek** [comment]
Okay, apart from the conflict that'll appear when bumping the version in `fog.gemspec` this is probably ready for merging.

So when merged and 1.8.7 support is officially dropped we can bump dependencies (#3099) and people can test with later Rails versions.

**Comment by agis-** [comment]
So any estimates on this? Thanks.

**Comment by tokengeek** [comment]
@agis- @geemus should be doing a release in the next few hours for the last 1.x release. Merging this then releasing a pre release version of 2.0.0-alpha for testing.

So by the end of Wes' day I hope.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
