### PR TITLE
Move contributing guidelines from fog.io to CONTRIBUTING.md

### LINKED ISSUE #3509: Contributing guidelines should move from fog.io to the GitHub repository
Per discussion in #3504, contributing guidelines should move from fog.io to the CONTRIBUTING.md guide in the GitHub repository, with a reference to that document on fog.io.

### PR DESCRIPTION
**Pull request by ihmccreery**
closes #3509

### CODE REVIEW

**Comment by plribeiro3000** [comment]
IMHO this should not go in the `CONTRIBUTING` since this file is used by `github`. It should be something small and just directions i guess. Perhaps we can move this to a wiki page and link form the website directly instead of a page with 1 line that gives you a link.

But i think that @tokengeek and @geemus are the best ones to give feedback on this.

**Comment by icco** [comment]
I don't know, I like this. Github just uses this doc by linking to it in new pull requests.

/Nat

**Comment by plribeiro3000** [comment]
@icco Hmmm. It does not seems to be a big deal so perhaps we can go forward with this.
Can you merge?

**Comment by geemus** [comment]
Seems good, thanks!

**Pull request merged**
