### PR TITLE
OpenStack provider gem

### PR DESCRIPTION
**Pull request by mdarby**
Hiya folks!

Lets move OpenStack into a provider gem. Questions? Concerns?

### CODE REVIEW

**Comment by jjasghar** [comment]
I like this idea. I'm willing to help out too we should sync @mdarby :metal:

**Comment by geemus** [comment]
Definitely support this. @fog/fog-openstack thoughts?

**Comment by Ladas** [comment]
Nice! I am gonna try it and update it in ManageIQ, to check if it doesn't break anything. :-)

**Comment by plribeiro3000** [comment]
:+1:

**Comment by seanhandley** [comment]
Thumbs up from me :+1:

**Comment by geemus** [comment]
Thanks! Will pull this in then.

**Comment by geemus** [comment]
@mdarby Where did the code move to/where is it now? Also, can you make sure I am one of the owners on the gem itself (probably same on rackspace stuff). Just want to make sure the organizational bits are lined up before I forget.

**Comment by mdarby** [comment]
Yea!!! The code now lives here: https://github.com/fog/fog-openstack.
And @geemus you're listed as an author on fog-rackspace and fog-openstack :)

**Comment by mdarby** [comment]
I've added @seanhandley, @Ladas, @jjasghar and @geemus to the `fog-openstack` repo as well :)
Thank you gents!

**Comment by geemus** [comment]
@mdarby cool, those locations were my (naive) guesses, just wanted to confirm. Thanks!

**Comment by Ladas** [comment]
@mdarby cool :+1: good job :-)

@mdarby @geemus do we have some rules on how many people do review, before we merge?

**Comment by geemus** [comment]
@Ladas no explicit rules. Try to have at least one reviewer though (ie not self-merging hopefully).

**Comment by Ladas** [comment]
@geemus ook, cool

**Comment by Ladas** [comment]
@mdarby @mdarby last question, who has the gem release rights now? I could use an ability to release more often than a monthly period. :-) E.g. releasing a new patch version before ManageIQ release can be a life saver sometimes. :-)

**Comment by mdarby** [comment]
Currently both @geemus and I are listed -- if you'd like access let me know your rubygems info :)

**Comment by Ladas** [comment]
@mdarby cool, this is me https://rubygems.org/profiles/Ladas

@mdarby @geemus btw. what are you guys using for bumping a gem version? It's been like 3 years since I did that last time. :-) I was using jeweler, seems like that project is not being developed for some time.

**Comment by mdarby** [comment]
hrm; I need your rubygems email (your redhat one isn't found)
As for bumping gem version I just manually update `version.rb` file -- and yeah `jeweler` is no more :(

**Comment by Ladas** [comment]
@mdarby smola.ladislav@gmail.com

Ook, I'll try the manual way

**Comment by mdarby** [comment]
Alrighty! You're listed on the gem :)

On Thu, Feb 25, 2016 at 10:47 AM, Ladislav Smola <notifications@github.com>
wrote:

> @mdarby <https://github.com/mdarby> smola.ladislav@gmail.com
>
> Ook, I'll try the manual way
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fog/fog/pull/3852#issuecomment-188848314>.
>



-- 


Cheers!


*Matt Darby, M.S.*
Web: matt-darby.com
Twitter: @mattdarby

**Comment by Ladas** [comment]
@mdarby awesome, thank you :-)

**Comment by geemus** [comment]
I sometimes do manual gem build stuff, but the bundler gem management stuff is really nice. Super easy to setup on new gems, I'm less sure how much work it would take to retrofit into something, but would be good to check out (I definitely use it with new gems).

**Comment by Ladas** [comment]
@geemus hmm, ok, I'll check it out, thank you :-)

**Pull request merged**
