### PR TITLE
[openstack] Removes URI::encode call on parameteres

### PR DESCRIPTION
**Pull request by petrblaho**
which causes NoMethodError in ruby's uri/rfc2396_parser.rb
when passed parameter's value is ie. Fixnum.

### CODE REVIEW

**Comment by geemus** [comment]
@fog/fog-openstack Could you review? Thanks!

**Comment by Ladas** [comment]
@geemus looks good, seems like the encoding is breaking things and it's not really needed. It's just on those few places plus few in service actions.

CI failure seems unrelated

**Comment by geemus** [comment]
@Ladas thanks, yeah, I really need to get the CI in order again.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
