### PR TITLE
[openstack] Fix for bad use of instance variables in a class method

### PR DESCRIPTION
**Pull request by dhague**
Thanks to @dLobatog for highlighting this at https://github.com/fog/fog/commit/4d5287020d961e794ac279c640c69a66238c33f7#commitcomment-14475988

### CODE REVIEW

**Comment by dLobatog** [comment]
:+1: , the only problem was that @identity_connection needed to be defined within an instance method, now it is defined properly.

**Comment by geemus** [comment]
Thanks!

**Comment by dLobatog** [comment]
@geemus is this expected for 1.37 or there is going to be a 1.36.1 release in between with changes like this?

**Comment by geemus** [comment]
Um, probably 1.37, though schedule-wise that theoretically would be Thursday in terms of timing.

**Pull request merged**
