### PR TITLE
[GleSYS] add support for SSH key management

### PR DESCRIPTION
**Pull request by tnn2**
Implements support for SSH key management in the GleSYS module as per:
https://github.com/GleSYS/API/wiki/Full-API-Documentation#sshkeyadd

### CODE REVIEW

**Comment by geemus** [comment]
I think in other parts of fog we have written this as `ssh_key` and `ssh_keys` (with an underscore in the middle). So for consistency I think maybe tweaking that might be a good call, what do you think?

**Comment by tnn2** [comment]
The reason things are named this way is to be consistent with the upstream API, which names it's parameter "sshkey" for the add request but stores it in the field "data" in the model. I don't object to changing it to be consistent with fog nomenclature though, if you think that's more appropriate.

**Comment by geemus** [comment]
Thanks for the clarification. I guess I would split it into two categories (this is what we do elsewhere in fog). For requests, keep the upstream spelling, these should map closely to one another. For collections/models though, we tend to try and follow the fog patterns (rather than upstream), so for those, the _ spelling would probably be preferred. This helps with interoperability for end users and keeps things consistent. Does that make sense? What do you think?

**Comment by tnn2** [comment]
That sounds reasonable, I will update the branch over the weekend.

**Comment by geemus** [comment]
Great, thanks!

**Comment by tnn2** [comment]
Hi, I renamed some things, please review again. Thanks!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
