### PR TITLE
Update getting_started

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**
Changed the example to use the new method. #3798

### CODE REVIEW

**Comment by geemus** [comment]
I think, actually, that we should change the server model to have a `destroy` method. That is what is expected for all models in fog and probably just got accidently overlooked here. Would you be up for adding the method here to do that? We should maybe also add a deprecation warning around using delete and have it call destroy. What do you think?

**Comment by h0lyalg0rithm** [comment]
Same here, its better to be consistent with the convention.
Deprecation warning would also be good.Maybe I should revert the change on the readme.

**Comment by geemus** [comment]
Sounds like a plan, just let me know if you have questions or there is
anything I can help with. Thanks!

On Mon, Dec 21, 2015 at 11:22 PM, Suraj Shirvankar <notifications@github.com

**Comment by h0lyalg0rithm** [comment]
@geemus Was a bit busy the past couple of days.Will try to send a PR soon hopefully before christmas.

**Comment by geemus** [comment]
No worries, thanks for the update.

On Wed, Dec 23, 2015 at 10:26 AM, Suraj Shirvankar <notifications@github.com

**Pull request closed without merging**
