### PR TITLE
[Docker] Adding multiple server support for Docker

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by geemus** [comment]
just let me know if you have questions or things I can help with.

**Comment by daviddavis** [comment]
@geemus thanks. I am planning on picking this back up on Monday. Want to test it out some more and then maybe write a test for this use case.

**Comment by daviddavis** [comment]
@geemus tested and it works. want to review my code?

**Comment by geemus** [comment]
Looks good, so far as I can tell code-wise anyway, lacking a docker setup to fully try on.

**Comment by geemus** [comment]
Thanks!

**Comment by daviddavis** [comment]
@geemus thanks!

**Pull request merged**
