### PR TITLE
Openstack security groups list typo

### PR DESCRIPTION
**Pull request by Ladas**
Openstack security groups list typo with elseif

### CODE REVIEW

**Comment by Ladas** [comment]
@geemus bad typo, do you think we can merge before release?

**Comment by geemus** [comment]
Oof, yeah that would be problematic.

**Comment by Ladas** [comment]
@geemus that was the last and our internal tests are passing \o/

Though it also doesn't cover everything. I will need to find time and do 100% requests and models tests coverage using VCR in Fog. That should catch all the stupid bugs. :-)

**Comment by geemus** [comment]
Definitely, sounds good. I believe tomorrow should be release day also, fwiw.

**Pull request merged**
