### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by blomquisg**
A couple fixes to internal calls that were causing deprecation warnings.

The warnings I was seeing were:

> Calling OpenStack[:compute].list_security_groups(server_id) is deprecated, use .list_security_groups(:server_id => value) instead

And,

> Calling OpenStack[:orchestration].list_resources(stack, options) is deprecated, call .list_resources(:stack => stack) or .list_resources(:stack_name => value, :stack_id => value) instead

### CODE REVIEW

**Comment by geemus** [comment]
Looks like there may be some test failures here, could you check into the travis run above? Thanks!

**Comment by blomquisg** [comment]
Yeah, I'll see if I can reproduce these locally.

**Comment by geemus** [comment]
Thanks, just let me know if you have questions. A quick glance at errors didn't make it totally obvious to me how it was related, but hopefully it will be clear with your closer inspection.

**Comment by blomquisg** [comment]
Found it ... the `Fog::Compute::OpenStack::Mock#list_security_groups` needed to be updated to handle the newer method signature.

**Comment by geemus** [comment]
Thanks!

**Comment by blomquisg** [comment]
Thanks @geemus!

**Pull request merged**
