### PR TITLE
[ovirt] Implement affinity groups

### PR DESCRIPTION
**Pull request by pdilung**
Implement affinity groups into _ovirt_ provider as described in https://github.com/abenari/rbovirt/issues/67 and https://github.com/abenari/rbovirt/pull/69.

### CODE REVIEW

**Comment by geemus** [comment]
Could we add some testing around this? I'm afraid otherwise it may be fragile and/or prone to future breakage.

**Comment by pdilung** [comment]
@geemus Yes, that is something I would like to do soon. As I wrote in #3435 I would need some help and time for this. Going to ask for it in next two weeks.
I would much appreciate if you could merge the PR before and I create tests PRs for #3435 and for this one as well :-)

**Comment by geemus** [comment]
Sounds like a plan, just let me know how I can help.

**Comment by pdilung** [comment]
Sure, thanks a lot.

**Pull request merged**
