### PR TITLE
Add missing attributes to stack and resource

### PR DESCRIPTION
**Pull request by bzwei**

### CODE REVIEW

**Comment by TerryHowe** [comment]
Are there updated docs that cover this.  These aren't mentioned in http://developer.openstack.org/api-ref-orchestration-v1.html

**Comment by bzwei** [comment]
Unfortunately the API page does not give example for resources. The example of stack does not include `parent` either. These attributes are visible with heat command line. For example:
```
+----------------------+----------------------------------------------------------------------------------------------------------------------------+
| Property             | Value                                                                                                                      |
+----------------------+----------------------------------------------------------------------------------------------------------------------------+
| capabilities         | []                                                                                                                         |
| creation_time        | 2015-04-20T19:31:48Z                                                                                                       |
| description          | Simple template to deploy a single compute instance                                                                        |
| disable_rollback     | False                                                                                                                      |
| id                   | 4869cc99-ec8d-413d-8d56-b4474a04e8ae                                                                                       |
| links                | http://10.13.214.218:8004/v1/9ae6444ca2d1470ea94b5c956ebf8b83/stacks/bill422-1/4869cc99-ec8d-413d-8d56-b4474a04e8ae (self) |
| notification_topics  | []                                                                                                                         |
| outputs              | []                                                                                                                         |
| parameters           | {                                                                                                                          |
|                      |   "network_id": "c38b58b9-b93c-4fc2-950a-52295dd1941c",                                                                    |
|                      |   "instance_type": "m1.tiny",                                                                                              |
|                      |   "OS::stack_id": "4869cc99-ec8d-413d-8d56-b4474a04e8ae",                                                                  |
|                      |   "OS::stack_name": "bill422-1"                                                                                            |
|                      | }                                                                                                                          |
| parent               | None                                                                                                                       |
| stack_name           | bill422-1                                                                                                                  |
| stack_owner          | admin                                                                                                                      |
| stack_status         | CREATE_COMPLETE                                                                                                            |
| stack_status_reason  | Stack CREATE completed successfully                                                                                        |
| template_description | Simple template to deploy a single compute instance                                                                        |
| timeout_mins         | None                                                                                                                       |
| updated_time         | None                                                                                                                       |
+----------------------+----------------------------------------------------------------------------------------------------------------------------+
```
and
```
+---------------+--------------------------------------+------------------+-----------------+----------------------+
| resource_name | physical_resource_id                 | resource_type    | resource_status | updated_time         |
+---------------+--------------------------------------+------------------+-----------------+----------------------+
| my_instance   | 9b03b9fd-2aa6-45ab-be54-e44b82546bba | OS::Nova::Server | CREATE_COMPLETE | 2015-04-20T19:31:48Z |
+---------------+--------------------------------------+------------------+-----------------+----------------------+
```

**Comment by TerryHowe** [comment]
lgtm

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
