### PR TITLE
Fixing gemspec conflicts with 1.9

### PR DESCRIPTION
**Pull request by Temikus**
First pass at fixing dependencies.

We really-really should think about dropping 1.9 sooner.

### CODE REVIEW

**Comment by Temikus** [comment]
Ok, so the bundle is at least stable now.

I see 1 test consistently failing:
```
Failure:
Fog::Compute::when ecloud is passed with no available credentials#test_0001_returns ArgumentError [/home/travis/build/fog/fog/spec/fog/compute_spec.rb:13]:
ArgumentError expected but nothing was raised.
```
And 3 flaky ones:
```
Fog::Storage::when aliyun is passed with no available credentials#test_0001_returns ArgumentError [/home/travis/build/fog/fog/spec/fog/storage_spec.rb:9]:
ArgumentError expected but nothing was raised.
```
```
Fog::Compute::when aliyun is passed with no available credentials#test_0001_returns ArgumentError [/home/travis/build/fog/fog/spec/fog/compute_spec.rb:13]:
[ArgumentError] exception expected, not
Class: <URI::InvalidURIError>
Message: <"bad URI(is not URI?): ">
---Backtrace---
/home/travis/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/uri/common.rb:176:in `split'
/home/travis/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
/home/travis/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-aliyun-0.1.0/lib/fog/aliyun/compute.rb:200:in `initialize'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/service.rb:108:in `new'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/service.rb:108:in `new'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:16:in `new'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/compute.rb:54:in `new'
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:4:in `[]'
/home/travis/build/fog/fog/spec/fog/compute_spec.rb:13:in `block (6 levels) in <top (required)>'
---------------
```
```
Fog::Compute::when vmfusion is passed with no available credentials#test_0001_returns ArgumentError:
Fog::Errors::MockNotImplemented: Contributions welcome!
    /home/travis/.rvm/gems/ruby-2.1.5/gems/fog-core-1.43.0/lib/fog/core/mock.rb:32:in `not_implemented'
    /home/travis/.rvm/gems/ruby-2.1.5/gems/fog-vmfusion-0.1.0/lib/fog/compute/vmfusion.rb:14:in `initialize'
    /home/travis/.rvm/gems/ruby-2.1.5/gems/fog-core-1.43.0/lib/fog/core/service.rb:108:in `new'
    /home/travis/.rvm/gems/ruby-2.1.5/gems/fog-core-1.43.0/lib/fog/core/service.rb:108:in `new'
    /home/travis/.rvm/gems/ruby-2.1.5/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:16:in `new'
    /home/travis/.rvm/gems/ruby-2.1.5/gems/fog-core-1.43.0/lib/fog/compute.rb:54:in `new'
    /home/travis/.rvm/gems/ruby-2.1.5/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:4:in `[]'
    /home/travis/build/fog/fog/spec/fog/compute_spec.rb:11:in `block (5 levels) in <top (required)>'
```
Is anyone familiar with those providers?

@plribeiro3000 PTAL

**Comment by Temikus** [comment]
One more flaky:
```
  Bluebox::BLB | lb_tests (bluebox) #  
  Fog::Compute[:bluebox] | block requests (bluebox) ########  
  Fog::Compute[:bluebox] | location requests (bluebox) ###  
  Fog::Compute[:bluebox] | product requests (bluebox) ###  
  Fog::Compute[:bluebox] | template requests (bluebox) ###  
  Fog::DNS[:bluebox] | DNS requests (bluebox, dns) ###############  
  Fog::Compute[:clodo] | image requests (clodo) +++  
  Fog::Compute[:clodo] | server requests (clodo) +++++++++++++  
  Fog::Compute[:cloudsigma] | server model (cloudsigma) ++++++++++  
  Fog::Compute[:cloudsigma] | servers collection (cloudsigma) #  
  Fog::Compute[:cloudsigma] | snapshot model (cloudsigma)       
      tests/cloudsigma/models/snapshot_tests.rb
        success
        Fog::Compute[:cloudsigma] | snapshot model (cloudsigma)
      - succeeds
      
      tests/cloudsigma/models/snapshot_tests.rb
      undefined method `[]=' for nil:NilClass (NoMethodError)
        /home/travis/build/fog/fog/lib/fog/cloudsigma/connection.rb:178:in `mock_create'
        /home/travis/build/fog/fog/lib/fog/cloudsigma/requests/create_snapshot.rb:22:in `create_snapshot'
        /home/travis/build/fog/fog/lib/fog/cloudsigma/models/snapshot.rb:35:in `create'
        /home/travis/build/fog/fog/lib/fog/cloudsigma/models/snapshot.rb:27:in `save'
        tests/helpers/model_helper.rb:8:in `block (2 levels) in model_tests'
        tests/helpers/succeeds_helper.rb:5:in `instance_eval'
        tests/helpers/succeeds_helper.rb:5:in `block in succeeds'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:140:in `instance_eval'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:140:in `assert'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:116:in `test'
        tests/helpers/succeeds_helper.rb:4:in `succeeds'
        tests/helpers/model_helper.rb:6:in `block in model_tests'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        tests/helpers/model_helper.rb:2:in `model_tests'
        tests/cloudsigma/models/snapshot_tests.rb:8:in `block in <top (required)>'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
        tests/cloudsigma/models/snapshot_tests.rb:1:in `<top (required)>'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
      
      tests/cloudsigma/models/snapshot_tests.rb
      identity is required for this operation (ArgumentError)
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/attributes.rb:155:in `requires'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/model.rb:40:in `reload'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/model.rb:70:in `block in wait_for'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:7:in `block in wait_for'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `loop'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `wait_for'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.43.0/lib/fog/core/model.rb:69:in `wait_for'
        tests/cloudsigma/models/snapshot_tests.rb:9:in `block (2 levels) in <top (required)>'
        tests/helpers/model_helper.rb:12:in `block in model_tests'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        tests/helpers/model_helper.rb:2:in `model_tests'
        tests/cloudsigma/models/snapshot_tests.rb:8:in `block in <top (required)>'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
        tests/cloudsigma/models/snapshot_tests.rb:1:in `<top (required)>'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
        /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
```

**Comment by geemus** [comment]
Thanks for looking into this. Agreed we should try to make 1.9 not be something we worry about.

**Comment by icco** [comment]
This relates to https://github.com/fog/fog/issues/3872.

**Comment by Temikus** [comment]
Ok, merging this to unblock people and will create a separate issue for flaky tests.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
