### PR TITLE
[vcloud_director] VM Network adapters

### PR DESCRIPTION
**Pull request by dbatwa**
- adding attribute on VM(s) to hold nics
- DRYing up vms and vm parsers

### CODE REVIEW

**Comment by dbatwa** [comment]
Hi Lovely ppl. Can we try and close this?

**Comment by geemus** [comment]
@dbatwa sorry for delay. It looks like this no longer merges cleanly though, could you rebase and we can try to get it in more quickly this time? Thanks!

**Comment by dbatwa** [comment]
Sure thing, will do it as quickly as possible.

**Comment by geemus** [comment]
Thanks, I'll try to make sure we don't lose track of it for so long this time around.

**Comment by dbatwa** [comment]
@geemus I've rebased and all vcloud_director tests are happy but failing on the latest HP removal.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
