### PR TITLE
Upgrade version of fog-vsphere to 0.4. Fixes #3784.

### LINKED ISSUE #3784: Fog::Mock.reset fails
With master, for some reason, `Fog::Mock.reset` throws the following exception: 

```
NameError: uninitialized constant Fog::Vsphere::Compute
from /Users/borski/.../gems/fog-core-1.35.0/lib/fog/core/mock.rb:96:in `const_get'`
```

Reproducing is very easy:
```
[1] pry(main)> require 'fog'
=> true
[2] pry(main)> Fog.mock!
=> true
[3] pry(main)> Fog::Mock.reset
NameError: uninitialized constant Fog::Vsphere::Compute
from /Users/borski/.../gems/fog-core-1.35.0/lib/fog/core/mock.rb:96:in `const_get'
```

No idea where it's coming from / how to fix it, or when it was introduced, but it's breaking some of my specs, sadly.

### PR DESCRIPTION
**Pull request by borski**
Fixes #3784

### CODE REVIEW

**Comment by borski** [comment]
Apologies - I'm a bit confused. I don't /think/ the failing builds have anything to do with my change? Correct me if I'm wrong?

**Comment by plribeiro3000** [comment]
@borski Could you try not to set a version but rather just limit the minimum version instead?

like `>= 0.0.4` ?

**Comment by borski** [comment]
@plribeiro3000 Updated. :)

**Comment by plribeiro3000** [comment]
Thanks!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
