### PR TITLE
[Azure cloud services | compute] initial release

### PR DESCRIPTION
**Pull request by ranjan**
Azure cloud  "Compute Service" Provider.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Hey @ranjan . Thank you for submitting this.

We are currently splitting `Fog` in smaller providers to make maintainability easier. So the best approach here would be to create a `fog-azure` gem. Are you up to do it?

**Comment by jeffmendoza** [comment]
Hi @plribeiro3000 Yes, this would be no problem for us. Which files should be a part of our gem?

Also, is there a list of fog provider gems that we could be on, once this is released?

**Comment by plribeiro3000** [comment]
@geemus Could you setup the repo?

@jeffmendoza You can take a look at another providers in the same organization of fog: https://github.com/fog.

**Comment by jeffmendoza** [comment]
@plribeiro3000 @geemus Sounds good, We'll work on the gem. Let us know when the repo is ready.

**Comment by geemus** [comment]
Repo is created. I added @ranjan and @jeffmendoza (you should get an email that will allow you to join the org and whatnot). Just let me know if anything doesn't work as expected or you have other questions or concerns. Thanks!

**Comment by jeffmendoza** [comment]
Thanks!!

**Comment by geemus** [comment]
I'm going to go ahead and close this since further stuff should be on the other repo, but just let me know if you need anything or I can help. Thanks!

**Pull request closed without merging**
