### PR TITLE
Fog support aliyun provider.

### PR DESCRIPTION
**Pull request by dengqinsi**
Fog support aliyun provider. 
CodePage: https://github.com/dtdream/fog-aliyun.git
Aliyun HomePage:  http://www.aliyun.com/

gem package:
gem install fog-aliyun

### CODE REVIEW

**Comment by dengqinsi** [comment]
Should install fog-aliyun first.
gem install fog-aliyun

**Comment by plribeiro3000** [comment]
Hey @dengqinsi . Thank you for your work!

Could you try to follow the conventions we are currently using?

* Use Autoload (See [here](https://github.com/fog/fog-xenserver/blob/master/lib/fog/xenserver.rb))
* Instead of define a core file with the content, define it on the main file of the gem.
* Could you add the comments in english instead? Otherwise most people can't really follow it. =s

Anyway. Really appreciate your efforts! Thanks!

**Comment by dengqinsi** [comment]
Thanks for your reply.
We fix the problems above:
  1. Use Autoload and have deleted core.rb in aliyun.
  2. All comments have been change to english or deleted(if not necessary).
See: https://github.com/dtdream/fog-aliyun.git
gem of fog-aliyun Update to version 0.0.7

**Comment by plribeiro3000** [comment]
@dengqinsi Awesome. Thank you for the fast reply. Now there is 2 steps more to follow. We need to  add the core maintainers (just in case) and move the repo under the `fog` organization.

Let me know when you add @geemus, @tokengeek and @krames to the rubygem.

As for the moving you can give me permissions on the repo so i can move it.

PS: would be good to tag the versions in git and github. I just noticed you have version 0.0.7 out but no tags exist in github.

**Comment by geemus** [comment]
@dengqinsi thanks!

@plribeiro3000 thanks for tackling this!

**Comment by plribeiro3000** [comment]
@geemus You are welcome!

**Comment by dengqinsi** [comment]
@plribeiro3000 I have add @geemus, @tokengeek and @krames to the rubygem for fog-aliyun.
fog-aliyun have added tag v0.0.7, and have invited you as owner.

**Comment by plribeiro3000** [comment]
Alright. I just moved the project to https://github.com/fog/fog-aliyun.
and i'm not part of your organization anymore so the first step is done. Now we need @geemus or @tokengeek to add the correct roles to the project and we are good to go.

**Comment by geemus** [comment]
I've made the team related tweaks.

**Comment by plribeiro3000** [comment]
Awesome. Thx @geemus

**Comment by plribeiro3000** [comment]
@dengqinsi Can you rebase your fork? It needs to include the latest fixes to the build.

**Comment by dengqinsi** [comment]
@plribeiro3000 10.1~10.7 is Chinese National Day and we do not work. i can not get into office. Can I fork a new work and submit new pull request?

**Comment by plribeiro3000** [comment]
Sure. Go for it!

**Comment by plribeiro3000** [comment]
Closing due #3172

**Comment by dengqinsi** [comment]
Update: Closing due #3712 :)

**Comment by geemus** [comment]
Thanks!

**Pull request closed without merging**
