### PR TITLE
Fix attach router to also use port id if passed

### PR DESCRIPTION
**Pull request by dhague**

### CODE REVIEW

**Comment by TerryHowe** [comment]
Alternatively, it could just take subnet id with optional port id, but this should work.

**Comment by geemus** [comment]
Is subnet_id required either way? Might be a less major change to just merge in the options?

**Comment by dhague** [comment]
I believe that passing subnet_id alone as a string (as opposed to within a hash) is actually a bug, but the behaviour was retained here for backward compatibility in case anyone is already using it.

**Comment by geemus** [comment]
Fair enough. Thanks!

**Pull request merged**
