### PR TITLE
Better help address for Rackspace

### PR DESCRIPTION
**Pull request by mdarby**

### CODE REVIEW

**Comment by mdarby** [comment]
@geemus Could you also please update http://fog.io to change the Rackspace support address to "https://developer.rackspace.com/support".

Thank you!

**Comment by plribeiro3000** [comment]
@mdarby You can do it by sending a PR to https://github.com/fog/fog.github.com. =)

**Comment by mdarby** [comment]
Thank you kindly; I shall do that now :)

**Comment by plribeiro3000** [comment]
It was a pleasure. Let me know if you need any help. =)

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
