### PR TITLE
OpenStack add nova service support

### PR DESCRIPTION
**Pull request by Ladas**
OpenStack add nova service API support.

### CODE REVIEW

**Comment by Ladas** [comment]
Working on running the tests with real env

**Comment by geemus** [comment]
Looks like a good start, just let me know how things are looking when you get a chance to work against real.

**Comment by Ladas** [comment]
@geemus real tests are passing now for services

**Comment by TerryHowe** [comment]
lgtm

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
