### PR TITLE
[DigitalOcean]  Added filtering capabilities to regions request.

### PR DESCRIPTION
**Pull request by rroa**
#3777 in the same way images were updated to support filtering, here's the same update for regions.

### CODE REVIEW

**Comment by rroa** [comment]
@bryanl @geemus

**Comment by geemus** [comment]
Could you update the mock stuff here as well? If you get it all to do the filtering stuff that would be great, but we should at least match up the method signatures. Thanks!

**Comment by rroa** [comment]
Sure, will do.

**Comment by rroa** [comment]
@geemus Updated!

**Comment by geemus** [comment]
Great, thanks!

**Pull request merged**
