### PR TITLE
[google] Add credentials tests

### LINKED ISSUE #3413: [google] Add support for JSON key format
Google introduced a new Service Account key format (JSON) and over time this will likely become the preferred format.  We should begin by supporting this new format soon. If Google does make this the default, we may want to follow-up and issue a (debug | info) warning to users relying on P12 format.

AFAIK, there is no clear documentation on this format. However, if you open up the Developers Console and look under "APIs & Auth" -> "Credentials", you'll see the "Generate New JSON Key" button next to any existing Service Accounts (or be given the option to create one with a new SA).

/cc @icco, @frodenas

### PR DESCRIPTION
**Pull request by frodenas**
Add credentials tests to Google provider.

This fixes #3413.

### CODE REVIEW

**Comment by frodenas** [comment]
@icco can you please review this PR?

**Comment by icco** [comment]
lgtm.

**Comment by geemus** [comment]
Thanks!

**Comment by danbroudy** [comment]
@frodenas is it ok if I grab this commit and apply it to the new fog-google repo in your name?

**Comment by frodenas** [comment]
@danbroudy Sure, go ahead, that was the plan (https://github.com/fog/fog/issues/3413#issuecomment-71379914).

**Pull request merged**
