### PR TITLE
OpenStack rename flavor extra specs to metadata

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Comment by TerryHowe** [comment]
@tzumainn the metadata rename thing I was thinking about.

**Comment by TerryHowe** [comment]
The purpose of this is to hide the inconsistency of the REST API and call flavor extra specs metadata which is more consistent with other OpenStack resources.

**Comment by mdarby** [comment]
Should :metadata be aliased :extra_specs for BWC?

**Comment by TerryHowe** [comment]
@mdarby they extra spec PR was merged yesterday.  it hasn't been released.

**Comment by mdarby** [comment]
Ah, I understand. Sorry for the noise.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
