### PR TITLE
[HPCloud] Removing HP cloud

### PR DESCRIPTION
**Pull request by jjasghar**
Per http://www.hpcloud.com/ the HP public cloud has been shutdown. There
still is the private cloud, but with the amount of changes that are
required and updated per instance, it would be easier to create plugins
for each.

Goodbye HP Cloud, we'll miss you.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Does this mean any of the apis supported here work anymore?

**Comment by plribeiro3000** [comment]
If so we might need to update the website as well.

**Comment by jjasghar** [comment]
@plribeiro3000 yep, that is correct. The HP Public Cloud is gone gone. We (Chef) removed our knife plugin too. https://github.com/chef/knife-hp

**Comment by plribeiro3000** [comment]
Nice. Thanks you for the PR then.
Could you open a PR against https://github.com/fog/fog.github.com and remove any references about it as well please?

Would be also nice to have something in the website and the README explaining it. Could you do this?

**Comment by jjasghar** [comment]
@plribeiro3000 consider it done. I'll have the PR and reference it here when it's completed.

**Comment by plribeiro3000** [comment]
Awesome! Thank you very much!

**Comment by geemus** [comment]
@jjasghar thanks! Going to go ahead and bring this in.

**Comment by jjasghar** [comment]
@geemus & @plribeiro3000 fyi: https://github.com/fog/fog.github.com/pull/47

**Pull request merged**
