### PR TITLE
[dynect] Move dynect bin from fog to fog-dynect.

### PR DESCRIPTION
**Pull request by glennpratt**
fog/fog-dynect#2 needs to land first.

### CODE REVIEW

**Comment by geemus** [comment]
Looks like there is a require to remove in `lib/fog/bin.rb` also (see failing tests). Could you also nuke that and make sure tests pass? Thanks!

**Comment by plribeiro3000** [comment]
I think you will need a new release of `fog-dynect` and then this will work. (the tests shall pass)

**Comment by glennpratt** [comment]
Released fog-dynect and updated with a version constraint.

**Comment by plribeiro3000** [comment]
this time the build will succeed.

**Comment by plribeiro3000** [comment]
There you go. =)

**Comment by plribeiro3000** [comment]
Thanks!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
