### PR TITLE
[Dynect] Extract Dynect DNS provider to fog-dynect.

### PR DESCRIPTION
**Pull request by glennpratt**
See #3646. Followed pattern in #3452.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@glennpratt Once you publish it, please add @geemus , @tokengeek and @krames to rubygems plz.

Thanks for all your work here! Very much appreciated!

**Comment by glennpratt** [comment]
@plribeiro3000 done, thanks. https://rubygems.org/gems/fog-dynect

**Comment by plribeiro3000** [comment]
Awesome. Thanks!

**Comment by plribeiro3000** [comment]
@glennpratt It did not trigger a build on travis. Can you do a push --force again? Thanks!

**Comment by glennpratt** [comment]
Looks like it's going now. I already had once. Guess it just needed a moment.

**Comment by glennpratt** [comment]
This openstack fail doesn't seem related.

**Comment by glennpratt** [comment]
Last known issue: I have the gem metadata pointing at https://github.com/fog/fog-dynect, which does not exist yet.

**Comment by plribeiro3000** [comment]
Awesome. I'm gonna go ahead and merge this!

Can you add @geemus as admin on your repo so he can move the repository?

Thanks!

**Comment by glennpratt** [comment]
@plribeiro3000 not sure I can. I can transfer ownership to him.

**Comment by plribeiro3000** [comment]
just give access to the repo them.

**Comment by plribeiro3000** [comment]
I think i might be able to do it as well. Try to add me so we can check. =)

**Comment by glennpratt** [comment]
@plribeiro3000 added you both as collaborators.

**Comment by plribeiro3000** [comment]
Hmm. it did not work. Maybe you can transfer ownership to `fog`?

**Comment by glennpratt** [comment]
"You don’t have admin rights to fog"

**Comment by plribeiro3000** [comment]
Damm. Then transfer it to me so i can transfer it to fog. lol

Maybe this works?

**Comment by glennpratt** [comment]
@plribeiro3000 "Repository transfer to plribeiro3000 requested"

**Comment by plribeiro3000** [comment]
@glennpratt Lets see if it works. If i don't have the rights as well i will just move it back to you. =)

**Comment by plribeiro3000** [comment]
It worked, just missing someone with owner access to give you access now. =)

**Comment by glennpratt** [comment]
@plribeiro3000 :+1: 

https://github.com/fog/fog-dynect

**Comment by glennpratt** [comment]
@plribeiro3000 also needs travis turned on to fix the badge. https://travis-ci.org/fog/fog-dynect

**Comment by plribeiro3000** [comment]
actually i don't have permissions on it anymore so i can't add travis as well. =s

**Comment by glennpratt** [comment]
Looks like everything is setup now. Thanks @geemus and @plribeiro3000!

**Comment by geemus** [comment]
Yep, took me a minute, but I think all the permissions/accesses are setup for fog-dynect anyway.

**Comment by geemus** [comment]
Thanks to both of you! Just let me know if I missed anything or there is anything more I can help with.

**Pull request merged**
