### PR TITLE
[google] Add support for JSON key format

### LINKED ISSUE #3413: [google] Add support for JSON key format
Google introduced a new Service Account key format (JSON) and over time this will likely become the preferred format.  We should begin by supporting this new format soon. If Google does make this the default, we may want to follow-up and issue a (debug | info) warning to users relying on P12 format.

AFAIK, there is no clear documentation on this format. However, if you open up the Developers Console and look under "APIs & Auth" -> "Credentials", you'll see the "Generate New JSON Key" button next to any existing Service Accounts (or be given the option to create one with a new SA).

/cc @icco, @frodenas

### PR DESCRIPTION
**Pull request by frodenas**
This fixes #3413.

@erjohnso, @icco I'm not sure if P12 format is deprecated, so I didn't add any *warning* message. We can add it later if it's finally deprecated.

### CODE REVIEW

**Comment by icco** [comment]
Would you be interested in adding some tests? This is quickly becoming a relatively complicated set of options...

**Comment by erjohnso** [comment]
@frodenas - thanks for this!!

P12 is not deprecated yet, so it's totally fine to not warn now.  However, it would probably be a good idea to update the docs (http://fog.io/compute/?#google-compute-engine). I'd suggest updating the code-snippet to use the JSON format, but mention in text that the P12 format is also supported.

As @icco said, it's getting a bit complicated, so better docs on the options will help users too.

**Comment by frodenas** [comment]
Agreed, I'll work on tests and docs hopefully this weekend.

**Comment by erjohnso** [comment]
Thanks Ferdy!

**Comment by icco** [comment]
(I can review docs as well. Docs are stored in https://github.com/fog/fog.github.com)

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
