### PR TITLE
Vcloud Director supports multiple VPN tunnels.

### PR DESCRIPTION
**Pull request by joshmyers**
Add support for them.

### CODE REVIEW

**Comment by joshmyers** [comment]
Any update on getting this merged?

**Comment by ajlanghorn** [comment]
I wonder if @mikepea has the ability to merge; if we ask him very nicely (hello Mike!), he might do the honours if he can... :)

**Comment by plribeiro3000** [comment]
Actually, i can merge. I just wonder where this is ok since i don't know anything about VCloud.

What sounds weird is that now you are working with an array but the name of the key is `Tunnel` (single). Is that what the Provider returns?

**Comment by joshmyers** [comment]
@plribeiro3000 I agree it does look weird but I followed what had been done for other `VcloudDirector` generators e.g. [LoadBalancerService](https://github.com/joshmyers/fog/blob/support_multiple_vpns/lib/fog/vcloud_director/generators/compute/edge_gateway_service_configuration.rb#L91)

The provider accepts `Tunnel` and I didn't want to break compatibility.

**Comment by plribeiro3000** [comment]
got it. Makes sense.Thx for bearing with me!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
