### PR TITLE
[Vsphere] added list/get compute resources functions

### PR DESCRIPTION
**Pull request by mingjin**
This patch is to add list/get compute resources of vsphere functions to fog. 

Usage:
to list all compute resources: compute.list_compute_resources
to just list effective compute resources(poweron + connected + not in maintenance state) : compute.list_compute_resources({:effective => true})
to get compute resources by name: compute.get_compute_resource('xxx.xxx.xxx.xxx')

Notice:
Vsphere abstracts clusters and hosts that don't belong to any cluster evenly as compute resource, so the return result may refer to either cluster or single host. If you want to get only hosts or clusters, you can use attribute 'isSingleHost' to determine the type.

### CODE REVIEW

**Comment by nirvdrum** [comment]
Generally this looks pretty good.  But it looks like @mingjin started committing unrelated stuff on top of the branch used for the pull request.

@mingjin Any chance you'd be willing to clean that up?

Barring that, I'll try to go through this when I have more time.  It will be a bit involved, but shouldn't take more than a day I'd think.

**Comment by mingjin** [comment]
Sure, we'd like to clean it up and create a separate PL later.


On Tue, Feb 3, 2015 at 8:21 AM, Kevin Menard <notifications@github.com>
wrote:

> Generally this looks pretty good. But it looks like @mingjin
> <https://github.com/mingjin> started committing unrelated stuff on top of
> the branch used for the pull request.
>
> @mingjin <https://github.com/mingjin> Any chance you'd be willing to
> clean that up?
>
> Barring that, I'll try to go through this when I have more time. It will
> be a bit involved, but shouldn't take more than a day I'd think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fog/fog/pull/1978#issuecomment-72567762>.
>



-- 
*Ming Jin*

Senior Consultant | *Thought*Works

Mobile: +86 186 2199 6300(China)
Gtalk: skyairmj@gmail.com
Twitter: https://twitter.com/mingjin
Weibo: http://weibo.com/imingjin

**Comment by nirvdrum** [comment]
Thanks!  Please comment back in the thread when you do so I'll get notified.

**Comment by mingjin** [comment]
Hi @nirvdrum,
I created a new PL #3426 with only related commits. I'm closing this PL. Please help approve the #3426 instead. Thanks,

**Comment by geemus** [comment]
Thanks!

**Comment by nirvdrum** [comment]
@mingjin Thanks!  The snapshot and other code looks interesting as well.  If you wouldn't mind additional pull requests, I'd be happy to review.

**Comment by mingjin** [comment]
@nirvdrum no problem. We'd love to contribute our code back to the community, including xenserver, hyper-v and etc. So glad to have your help on this and future pull requests :)

**Comment by plribeiro3000** [comment]
@mingjin Take a look at [`fog-xenserver`](https://github.com/fog/fog-xenserver).

We already extracted it but did not remove the support on fog due the refactoring and api backward compatibility breaking we have to do to improve the codebase. All apis that will change are deprecated in fog anyway.

**Comment by mingjin** [comment]
@plribeiro3000 thanks for your reminder. Will check out the fog-xenserver repo and follow the new way.

**Comment by plribeiro3000** [comment]
@mingjin :+1:

**Comment by mingjin** [comment]
@plribeiro3000 
It seems the new fog-xenserver changes a lot in the code structure and names. If we want to submit our code, do we need to create two respective pull requests in two repos for the time being? Any plan to completely retire the xenserver code in fog?

**Comment by plribeiro3000** [comment]
The code in `Fog` is already deprecated. Should be good to cut after next release.
I would suggest you to forget about the current implementation in `Fog` since it way to old.

Let's work on top of `fog-xenserver` and keep the code here the way it is.

**Pull request closed without merging**
