### PR TITLE
Fixes #3084: Implement OpenStack Identity V3 API

### LINKED ISSUE #3084: Domain support in Identity v3
With the Identity v2.0 API marked as deprecated in Icehouse (alltho reverted after release), cloud providers are starting to require using the v3 API to authenticate.

This is needed to support domains, to achieve full multi-tenancy in public clouds.

The v2.0 API seems to be scheduled for removal in the Kilo release next year.

Please look into supporting v3 and domains.

Documentation for the v3 API:
* http://api.openstack.org/api-ref-identity-v3.html

Aviator support for v3 API:
* https://github.com/aviator/aviator/blob/master/lib/aviator/openstack/identity/requests/v3/public/create_token.rb

### PR DESCRIPTION
**Pull request by dhague**
Fog::Identity::OpenStack.new() will return either a V2 API object or a V3 API object depending on the auth URL
Fog::OpenStack::Core.authenticate switches on the auth URL to call the V2 or V3 authentication API

Travis should be happy with this one! :)

### CODE REVIEW

**Comment by dhague** [comment]
\o/

**Comment by plribeiro3000** [comment]
Awesome @dhague, thanks!

Lets wait for someone with proper knowledge on Openstack to review your code now.

**Comment by TerryHowe** [comment]
working for me

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
