### PR TITLE
Move Rackspace out to provider gem

### PR DESCRIPTION
**Pull request by mdarby**
I've moved all Rackspace logic out into a provider gem named `fog-rackspace`.
The repo is here: https://github.com/fog/fog-rackspace
All tests passing locally!

### CODE REVIEW

**Comment by mdarby** [comment]
Seems the failed tests are the same that `master` is experiencing?

**Comment by plribeiro3000** [comment]
@mdarby I remember that in the past your users could not have `fog-rackspace` without the `fog` console. Is this still a problem?

**Comment by plribeiro3000** [comment]
And regarding the dependencies like you have:

```ruby
spec.add_dependency 'fog-core',  '~> 1.27'
spec.add_dependency 'fog-json',  '~> 1.0'
spec.add_dependency 'fog-xml',   '~> 0.1'
```

i would say to not be pessimistic that way otherwise we might get conflicts when other providers get other specific versions. If you have a minimum version you need to make your features work use it as the minimum version like:

```ruby
spec.add_dependency 'fog-core',  '>= 1.27'
spec.add_dependency 'fog-json',  '>= 1.0'
spec.add_dependency 'fog-xml',   '>= 0.1'
```

BTW, `fog` `1.27` is quite old.

**Comment by plribeiro3000** [comment]
After the dependecy stuff is fixed and if you don't have a problem by not having the `fog` console available yet i would say this is good to be merged. =)

**Comment by mdarby** [comment]
heh, I lifted those dependencies from the `fog-aws` gem. I'll update those.

The `fog` console is working! 
1 fog 2016-02-16 18-26-39

**Comment by plribeiro3000** [comment]
@mdarby Even when you have only `fog-rackspace` in your gemfile? I'm not sure it should work without some code that is in the main `fog` gem only.

**Comment by mdarby** [comment]
Hrm, will dig into the console tonight. :)

**Comment by mdarby** [comment]
In order to test the `fog` console in this case I've done the following:

`gem uninstall fog` (all)
`gem build fog.gemspec` (from this branch)
`gem install fog-1.37.0.gem`
`fog`
`Fog::Rackspace::BlockStorage.new`
fog 2016-02-17 11-49-43

Does this process seem correct?

**Comment by mdarby** [comment]
If I only add `fog-rackspace` to the `Gemfile` and run `bundle exec fog` it asks for me to install the `fog` gem. I add that and all works as expected.

**Comment by plribeiro3000** [comment]
Thats what i'm saying. `fog-rackspace` wont work out of the box without the main `fog` gem.
If thats not a problem. we can move on with this. Just wanted to make sure that we can't make `fog` a dependency of any of the providers (`fog-rackspace`).

**Comment by mdarby** [comment]
If I just add `fog-rackspace` to the `Gemfile` I can load up `irb` and it works. I don't think fog's console is an issue. I'd never even heard of it?

**Comment by plribeiro3000** [comment]
Then we are good. =)

**Comment by plribeiro3000** [comment]
@mdarby Could you now make it complain to our current setup?
Take a look a [this page](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch) for further instructions.

**Comment by mdarby** [comment]
Alrighty! I've added everything from https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch and have pushed to https://github.com/fog/fog-rackspace

**Comment by plribeiro3000** [comment]
@mdarby You are missing the usage of `autoload` at the main file [here](https://github.com/fog/fog-rackspace/blob/master/lib/fog/rackspace.rb#L5-L23) and the `CONTRIBUTORS` file is kind of broken (but i guess the wiki page was not explaining it correctly). See an example of the `CONTRIBUTORS` file [here](https://github.com/fog/fog-xenserver/blob/master/CONTRIBUTORS.md).

**Comment by mdarby** [comment]
I've updated the main file to use `autoload` over `require`.

**Comment by plribeiro3000** [comment]
@mdarby Nice. The autoload thing was the most important point since we got a serious loading issue before because of it.

**Comment by plribeiro3000** [comment]
:+1:

**Comment by mdarby** [comment]
Wooo! Thank you sir!

**Comment by geemus** [comment]
Awesome, thanks!

**Comment by geemus** [comment]
@mdarby could you add me as an owner on fog-rackspace gem? I just like to have that as a just-in-case, should I need to do security or other emergency releases or if there are weird dependency issues or whatever. Thanks!

**Comment by mdarby** [comment]
Added! :)
https://rubygems.org/gems/fog-rackspace

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
