### PR TITLE
Tuskar docs and examples

### PR DESCRIPTION
**Pull request by petrblaho**
This PR adds brief docs and few examples for Planning service for OpenStack.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@petrblaho Is this `Tuskar` service implemented?

**Comment by petrblaho** [comment]
@plribeiro3000 yes. See #3440 and #3498 .

**Comment by plribeiro3000** [comment]
@petrblaho Thank you for the links. =)

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
