### PR TITLE
Removing ovirt provider

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@orrabin Is the extraction for `fog-ovirt` done already?

**Comment by orrabin** [comment]
@plribeiro3000 yes it's now in https://github.com/fog/fog-ovirt

**Comment by orrabin** [comment]
@plribeiro3000 I added you and @geemus as owners in rubygems.
Should the gem version be 0.1.0 or 1.0.0 right away?

**Comment by plribeiro3000** [comment]
Just release a `0.1.0` version so everyone will know it is not in prototype. =)

**Comment by plribeiro3000** [comment]
Thank you for the efforts on this!

**Comment by plribeiro3000** [comment]
Ouch. I forgot to ask to add `fog-ovirt` as a dependency. 

@orrabin Can you send another PR adding it as a dependency?

**Comment by geemus** [comment]
@orrabin thanks for helping set all that up, now we just need to add it as a dependency in fog and I think we'll be ready to go.

**Comment by orrabin** [comment]
@plribeiro3000 I thought I did by adding it to the gemspec: https://github.com/fog/fog/pull/3962/files#diff-ebc7a16e41d6b42010f22cf407abfec8R70 and it was already [required](https://github.com/fog/fog/blob/6aa670e9b3778f7b8121e50b91df37eacff8f946/lib/fog.rb#L48)
is there any other place I should update?

**Comment by plribeiro3000** [comment]
Ouch.

I guess the diff was to big so i missed it somehow. My bad.

We are good to go here!

**Comment by geemus** [comment]
Awesome, thanks for clarifying.

**Comment by orrabin** [comment]
@plribeiro3000 we now have version 0.1.0 for fog-ovirt :)

**Comment by plribeiro3000** [comment]
@orrabin Awesome. Thanks!

**Comment by geemus** [comment]
Thanks!

**Comment by iNecas** [comment]
@geemus any estimates on when to expect a new fog release including this change?

**Comment by geemus** [comment]
@iNecas I traveled last week and have been playing catchup every since, but soon I hope.

**Comment by geemus** [comment]
just released 1.42.0

**Comment by iNecas** [comment]
Thanks a lot @geemus !

**Pull request merged**
