### PR TITLE
Change openstack_prj to openstack_project

### PR DESCRIPTION
**Pull request by TerryHowe**
It is hard to remember odd abbreviations.

### CODE REVIEW

**Comment by TerryHowe** [comment]
@clarsonneur

**Comment by geemus** [comment]
Seems good. Maybe we should support the old way also for backwards compatibility? (I can't recall now if the old way made it into a release, if not this is probably not a big deal and maybe isn't that big of a deal anyway). What do you think?

**Comment by TerryHowe** [comment]
I don't think this v3 auth has been released yet, so no need for backwards compat.

**Comment by geemus** [comment]
Sounds good. Thanks!

**Comment by clarsonneur** [comment]
hello! thank you for this! Sorry, as I was out for sometimes. So I was not able to do it myself.

**Pull request merged**
