### PR TITLE
[OpenStack|Network] Preliminary Meter Support

### PR DESCRIPTION
**Pull request by Matt1360**
This just goes over four of the [Neutron Meter](https://wiki.openstack.org/wiki/Neutron/Metering/Bandwidth) commands.  I'm using it for some stuff, and wanted to see if it would be useful to anyone else.

### CODE REVIEW

**Comment by geemus** [comment]
Seems like a good start, but could use some tests around these?

**Comment by Matt1360** [comment]
Yep! :)

I want to clean this up a little more, and maybe add a few more requests to it.  I'll try to add some tests in this week at the same time.

**Comment by geemus** [comment]
Sounds great, just let me know if you have questions or need help. Thanks!

**Comment by plribeiro3000** [comment]
@Matt1360 Could you open this against `fog-openstack` instead please?

Thanks!

**Pull request closed without merging**
