### PR TITLE
add endpoints and services support to openstack identity service

### PR DESCRIPTION
**Pull request by scambra**
I have added requests and models for service and endpoint using OpenStack Identity API

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@geemus Is there someone we can summon here?

**Comment by geemus** [comment]
@mdarby - could you take a look perhaps? Thanks!

**Comment by plribeiro3000** [comment]
@scambra Can you add some tests around this?

**Comment by mdarby** [comment]
LGTM

**Comment by scambra** [comment]
I'm very busy right now, maybe in some weeks, I don't know if someone can pick this changes and add some tests, it shouldn't be hard

**Comment by geemus** [comment]
Thanks for the update.

**Comment by Temikus** [comment]
Looked through `fog-openstack`, identity services seem to be correctly added already.
I think this can be closed.

I ported over the net_id fix though for the maintainers to look at. Thanks @scambra!
 
/CC @plribeiro3000

**Comment by plribeiro3000** [comment]
:+1:

Em ter, 28 de jun de 2016 06:34, Artem Yakimenko <notifications@github.com>
escreveu:

**Comment by plribeiro3000** [comment]
Closing. Thx!

**Pull request closed without merging**
