### PR TITLE
OpenStack expose header information in image download

### PR DESCRIPTION
**Pull request by Ladas**
We need some header information like checksum, Accept-Ranges etc

Also exposing the Range header, for partial downloads

### CODE REVIEW

**Comment by Ladas** [comment]
@roliveri please try if this works for you. On my OpenStack kilo, it probably doesn;t support ranges. It shoudl return in header Accept-Ranges: bytes. Maybe some Glance V2 configuration is needed first?

The example call for partial get with header returned should look like
body, header = image.download_data(:return_header => true, :content_range => "bytes=0-100")

**Comment by jjasghar** [comment]
Kick this over to fog/fog-openstack?

**Comment by plribeiro3000** [comment]
Good point @jjasghar. =)

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#35

**Pull request closed without merging**
