### PR TITLE
Adding OpenStack Host Aggregate support

### PR DESCRIPTION
**Pull request by Ladas**
Adding OpenStack host aggregate support

### CODE REVIEW

**Comment by Ladas** [comment]
working on real tests

**Comment by Ladas** [comment]
real tests are passing now

**Comment by TerryHowe** [comment]
lgtm

**Comment by plribeiro3000** [comment]
@Ladas @TerryHowe Is this something we could add more tests perhaps?

**Comment by geemus** [comment]
Seems sufficient, at least for now. Thanks!

**Pull request merged**
