### PR TITLE
[openstack][Storage] Added the delete_at and delete_after flags

### PR DESCRIPTION
**Pull request by razorinc**
I provided the functionality for the delete_at and delete_after into the OpenStack provider, since was currently missing from the project. //cc @Ladas if you've bandwidth to look at it, would be awesome.

### CODE REVIEW

**Comment by TerryHowe** [comment]
lgtm.  I always thought that was a cool feature.

**Comment by Ladas** [comment]
lgtm :+1:

**Comment by razorinc** [comment]
@TerryHowe @Ladas kudos fellas :)

**Comment by geemus** [comment]
Cool, thanks!

**Pull request merged**
