### PR TITLE
Missing network init uri

### PR DESCRIPTION
**Pull request by Ladas**
Missing network init uri, got lost probably in cleanup in
https://github.com/fog/fog/commit/83b61986bd2787dd22dc8967f28d0c78d8752aff

### CODE REVIEW

**Comment by Ladas** [comment]
@dhague you probably forgot it while doing the cleanup https://github.com/fog/fog/commit/83b61986bd2787dd22dc8967f28d0c78d8752aff

I am getting exception with missing uri

**Comment by dhague** [comment]
Good catch, thanks - might it be better to put that line into the initialize_identity method so that it's picked up for other openstack services?

**Comment by Ladas** [comment]
@dhague yeah I guess we could set it in authenticate method, where the code is now

so e.g. @openstack_management_uri = URI.parse(@openstack_management_url) ?

**Comment by Ladas** [comment]
@dhague changed, something like this was on your mind?

**Comment by dhague** [comment]
That will do the job nicely :)

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
