### PR TITLE
fixes issue #3458 - search vm also by 'raw_datacenter.find_vm'

### PR DESCRIPTION
**Pull request by shlomizadok**
Searches vm either with ```get_vm_by_name``` or ```raw_datacenter.find_vm```

### CODE REVIEW

**Comment by shlomizadok** [comment]
@nirvdrum - Thoughts on this pr?

**Comment by nirvdrum** [comment]
Thanks.  It might be a few days before I get to take a look.  But I'll try to get to it sooner rather than later.

**Comment by shlomizadok** [comment]
@nirvdrum ping?

**Comment by nirvdrum** [comment]
Sorry, my cluster had gone to hell and I got side-tracked getting that back up.  I'm now looking at all fog issues assigned to me.

**Comment by nirvdrum** [comment]
@shlomizadok Thanks for taking the time to come up with a PR and for being patient with me.  I looked at what you had, and while it was technically correct, I wanted to try to fix the core problem with the get_vm_by_name method to try to cut down on the number of branches we take.  I committed that as 6f205bbe0cb9dd2fab3c6b0d371b9933aba41507.

That change seems to fix #3458 for me.  If you could verify that it fixes the problem for you, that would be very helpful.  Naturally if it works, we won't need to merge your PR.  But if it doesn't, I'll revert what I have and merge yours.

**Comment by geemus** [comment]
@nirvdrum sorry to hear about the cluster, glad it has resolved so you could rejoin us. Thanks!

**Comment by shlomizadok** [comment]
Closing this in favor of https://github.com/fog/fog/commit/6f205bbe0cb9dd2fab3c6b0d371b9933aba41507

**Pull request closed without merging**
