### PR TITLE
[openstack|compute] added support for flavor extra_specs

### PR DESCRIPTION
**Pull request by tzumainn**
Adds support for getting and creating extra_specs for an OpenStack
flavor.

### CODE REVIEW

**Comment by mdarby** [comment]
:+1:

**Comment by plribeiro3000** [comment]
hey @tzumainn. Could you add some tests around this? Thanks!

**Comment by TerryHowe** [comment]
This might be one of those areas that Fog should hide the inconsistency of the REST API naming and call this flavor metadata or something.

**Comment by tzumainn** [comment]
@plribeiro3000 Ah, yep, I'll add tests in
@TerryHowe That seems reasonable - should I go ahead and do that now, or do others need to weigh in as well?

**Comment by tzumainn** [comment]
@plribeiro3000 tests added

**Comment by plribeiro3000** [comment]
Seems pretty simple to me. I'm not that into Openstack but since @mdarby says its ok i will go ahead and merge!

Thank you @tzumainn !

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
