### PR TITLE
adding version attribute for ovirt template

### PR DESCRIPTION
**Pull request by unorthodoxgeek**
adding the version attribute for ovirt templates (templates can have the same name, with different versions)

### CODE REVIEW

**Comment by unorthodoxgeek** [comment]
this relies on code I've contributed to rvovirt and it's wrong.

**Comment by geemus** [comment]
Just let me know if there is anything around this I can help with. Thanks!

**Comment by unorthodoxgeek** [comment]
I broke the code on another repo and thought the fault was in fog, reopening,

**Comment by geemus** [comment]
@unorthodoxgeek no worries, easy mistake to make. Will we need to wait for some changes in ovirt before we bring this in then?

**Comment by unorthodoxgeek** [comment]
@geemus - maybe I wasn't wrong.
The template version isn't a simple string, it has three attributes, so instead of passing a string I'm now passing an object which has three methods (base_template, version_number and version_name). What I'm getting is the inspect string of that object... ("#<OVIRT::TemplateVersion:0x007f9756088758>"), which is unexpected...
am I doing something wrong?

**Comment by geemus** [comment]
@unorthodoxgeek - that is probably fine actually. It is kind of naive and so I think when it inspects objects it just recursively calls inspect (which would result in what you describe), but that the actual data there would be the object, not the inspect/string. Does that help/make sense?

**Comment by unorthodoxgeek** [comment]
what happens is that template.version returns "#OVIRT::TemplateVersion:0x007f9756088758" instead of the OVIRT::TemplateVersion instance...

**Comment by geemus** [comment]
Ah... hmm. That I am not sure about. I would suspect something about the value being passed in, rather than conversion within the model, but I could be wrong.

**Comment by unorthodoxgeek** [comment]
just to test, I've passed in a hash, that works as expected... I'll investigate further tomorrow :)

**Comment by geemus** [comment]
@unorthodoxgeek cool, yeah that aligns with my expectations. Sounds like a plan, just let me know if there is anything else I can help with. Thanks!

**Comment by unorthodoxgeek** [comment]
eureka. the compute class does to_s, which makes little sense to me, but I guess it makes some sense.
tests will probably fail until rbovirt will get updated, so don't merge this yet

**Comment by unorthodoxgeek** [comment]
ok, this change should work once the rbovirt gem is updated to 0.0.32 - how can we do this?

**Comment by geemus** [comment]
@unorthodoxgeek since not everyone needs rbovirt, I think we depend on the end-user installing it independently. The tests, however, are a different story. You should be able to update the development dependency here: https://github.com/fog/fog/blob/master/fog.gemspec#L81

**Comment by unorthodoxgeek** [comment]
@geemus - updated, a test failed on openstack on one of the runs, I believe it's okay though, isn't it?

**Comment by geemus** [comment]
@unorthodoxgeek yeah, that one fails intermittently for some reason...

Thanks!

**Comment by unorthodoxgeek** [comment]
@geemus - any idea when this will enter a published version? we at foreman are depending on this for a rather important issue...

**Comment by geemus** [comment]
@unorthodoxgeek sorry. I am working on catching up to a bit of issue/PR backlog, but hope to release after that. I'm optimistic that it might be as early as this afternoon, but it might end up being tomorrow. Hopefully by the end of the week regardless.

**Pull request merged**
