### PR TITLE
[vsphere] add support for taking snapshot

### PR DESCRIPTION
**Pull request by ireznice**
Hi,
 
This is the first improvement of vsphere provider for fog. It adds the ability to take snapshot only, it simply adds take_snapshot method to compute model.
 
The functions list_snapshot and revert to snapshot will follow in the future.
 
Best regards
ireznice

### CODE REVIEW

**Comment by ireznice** [comment]
The Travis-ci testing failed but fails encountered are related to another provider, is that pullrequest mergable?

**Comment by plribeiro3000** [comment]
@ireznice Could you add some tests around this please?

**Comment by ireznice** [comment]
@plribeiro3000 The requested changes were added.

**Comment by plribeiro3000** [comment]
@ireznice LGTM. Just need to take care of travis which is failing so i can be sure it all good here. :+1:

**Comment by plribeiro3000** [comment]
@ireznice All green now. Thank you!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
