### PR TITLE
[openstack|identity] check_token and validate_token - make tenant_id opt...

### LINKED ISSUE #3493: [openstack] Fog::Identity::Openstack check_token and validate_token should not require mandatory tenant_id
The methods check_token and validate_token require a tenant_id parameter, but according to http://developer.openstack.org/api-ref-identity-v2.html this parameter is optional. This means that unscoped tokens cannot be validated/checked using Fog.

### PR DESCRIPTION
**Pull request by dhague**
...ional

Fixes #3493

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@dhague Could you add some tests around this changes?

**Comment by dhague** [comment]
Sure - could you point me to any other tests for OpenStack in Fog so I know where to start?

**Comment by plribeiro3000** [comment]
@dhague :+1:

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
