### PR TITLE
Fix comment: 5mins = 300s

### PR DESCRIPTION
**Pull request by ajlanghorn**
Fixes the comment to accurately reflect how many seconds are in five
minutes.

### CODE REVIEW

**Comment by TerryHowe** [comment]
:+1:

**Comment by plribeiro3000** [comment]
Hmm. actually the code is using `600`. Maybe it should say 10 minutes?

I don't remember exactly how the method `wait_for` syntax.

**Comment by ajlanghorn** [comment]
@plribeiro3000 Oh, darn; you're right. I can either up the limit, or change the comment... which is preferred?

**Comment by plribeiro3000** [comment]
I think its better to just change the comment. Since the code is this way it might have a reason. =)

Just looked at the implementation [here](https://github.com/fog/fog-core/blob/d117cd252d28b6b6d411043b6766413e260898db/lib/fog/core/wait_for.rb#L2) and it turns out that we have an interval of `600` and an interval of `5`. =)

**Comment by ajlanghorn** [comment]
@plribeiro3000 Good call; thank you. I've repushed.

**Comment by plribeiro3000** [comment]
Awesome. Thanks. 

I gotta have to take a look at this build. Sometimes it fails, sometimes not. =s

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
