### PR TITLE
Fix dependency issues when building

### PR DESCRIPTION
**Pull request by plribeiro3000**
Ok. Now all builds succeed to install all dependencies but we still have some broken tests but we can use #3933 for that. =)

### CODE REVIEW

**Comment by plribeiro3000** [comment]
I'm gonna go ahead and merge since this is just a build change, mostly on travis.

**Comment by plribeiro3000** [comment]
cc/ @Temikus @icco @geemus @tokengeek Do you know where does the dependency `public_suffix` come?

I did install old ruby versions on my machine and did a clean install without it but travis keep complaining it could not install it so i had to force its version. =s

**Comment by geemus** [comment]
afraid I'm not sure off hand, gemfile lock should maybe show in some way?

**Comment by plribeiro3000** [comment]
I thought the same. The issue is that locally it does not install it but in
Travis it does. Is there a way to see the build in Travis (I mean the
artifacts and files)?

Em sex, 24 de fev de 2017 12:17, Wesley Beary <notifications@github.com>
escreveu:

**Comment by icco** [comment]
@plribeiro3000 you could always add `cat Gemfile.lock` to the script block. You could also get complicated with https://docs.travis-ci.com/user/uploading-artifacts/

**Pull request merged**
