### PR TITLE
fix openstack baremetal node delete

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
From http://docs.openstack.org/developer/ironic/webapi/v1.html 
 DELETE /v1/nodes

    Delete a node.
    Parameters:	

        node_ident (uuid_or_name) – UUID or logical name of a node.

When this line is node_uuid response is:
irb(main):009:0> undercloud_handle.delete_node('3a7902bb-d91f-48c5-aa53-f046f309e84f')
Excon::Errors::BadRequest: Expected([200, 204]) <=> Actual(400 Bad Request)
  response => #<Excon::Response:0x00000002536fb8 @data={:body=>"{\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"Unknown argument: \\\\\\\"node_uuid\\\\\\\"\\\"}\"}", ...

**Comment by geemus** [comment]
@dhague @Ladas @TerryHowe - could one of you review? Thanks!

**Comment by Ladas** [comment]
@jmontleon ah, good catch

Looks good to me :+1:

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
