### PR TITLE
Require fog-google versions compatible w/ > 1.9.3

### PR DESCRIPTION
**Pull request by icco**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
I wonder if we need to be pessimistic here. Maybe we could use `>=` and avoid future need to update the dependencies. This way the user can tweak the provider versions for its own need. What do you think?

**Comment by icco** [comment]
That's fair, I'm totally down with that. I also fucked up that release by not adding the ruby version limiter. Will fix.

**Comment by icco** [comment]
Fixed @plribeiro3000.

**Comment by plribeiro3000** [comment]
Awesome. Thx for bearing with me @icco

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
