### PR TITLE
[GleSYS] Xen is deprecated use VMware instead

### PR DESCRIPTION
**Pull request by Artmann**
GleSYS has deprecated their Xen Platform and VMware is now recommended instead.

* Change the default values when creating a server to use Debian 7 64-bit on OpenVZ.
* Change the tests to create severs on OpenVZ and VMWare instead of OpenVZ and Xen.
* Update the test so they are consistent with the GleSYS API.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@Artmann Note `Xenserver` is not `deprecated`. Part of the api is deprecated. Xenserver support will keep working as always.

**Comment by Artmann** [comment]
@plribeiro3000 Are you talking about fog/xenserver? This pullrequest only apply to the GleSYS portion of the fog providers.

**Comment by plribeiro3000** [comment]
Ouch. I miss read your comment in the PR. Sorry about that. Does this change work as expected?
If so i'm gonna go ahead and merge this.

**Comment by Artmann** [comment]
Yes it's working as expected

**Comment by plribeiro3000** [comment]
Awesome. Thanks!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
