### PR TITLE
Fix digitalocean bin issue

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**
Sorry for introducing the error in the first place.This should fix it. :sob:

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Thats ok. =)

Regarding the tests it would be good to maintain them at least for now. Those were added by @tokengeek as a way to make sure the extracted providers are working as they should.
I believe we fixed this by adding the binary in `fog-digitalocen`.

**Comment by h0lyalg0rithm** [comment]
Got it will try to fix it in the fog-digitalocean repo

**Comment by plribeiro3000** [comment]
Sure. I believe @Temikus fixed it already. The issue now rely on `json` not being able to install. =s

**Comment by h0lyalg0rithm** [comment]
Oh.Didnt look at travis.Seems like its still failing on my machine.probably some setup issue.

**Pull request closed without merging**
