### PR TITLE
[DigitalOcean] Added filtering capabilities to servers request.

### PR DESCRIPTION
**Pull request by rroa**
#3777 in the same way images were updated to support filtering, here's the same update for servers.

### CODE REVIEW

**Comment by geemus** [comment]
Could you update the method signature for the mock version also? If you can update the mock version to do the right thing there that would be even better, but the difference in signature is likely to cause problems, so at least fixing that would be good. Thanks!

**Comment by rroa** [comment]
Sure, will do.

**Comment by rroa** [comment]
@geemus I'm having trouble finding the mocks you're referring to. I don't have much experience with shindo, as I have two PR's waiting for a similar update could you point me on the right direction for this one? 

I assumed it was at **tests/digitalocean/requests/compute_v2/list_serversL:69** but wanted to make sure it was just doing something like `tests('#list_servers(#{filters})')`

**Comment by geemus** [comment]
@rroa actually, I just meant in the request definitions (I think the tests should be fine). In particular in the request files, there should be two defined methods (a real version and a mock version). So the method signature I was referring to updating, in this case, would be here: https://github.com/rroa/fog/blob/bugfix/do_servers_filters/lib/fog/digitalocean/requests/compute_v2/list_servers.rb#L16

Hope that clarifies, but just let me know if you have further questions or concerns. Thanks!

**Comment by rroa** [comment]
@geemus  Thanks for the help. I have updated the signature at the Mock to match the new changes.

**Comment by geemus** [comment]
Great, thanks!

**Pull request merged**
