### PR TITLE
Remove internet_archive

### PR DESCRIPTION
**Pull request by icco**
For #3942, dependent on https://github.com/fog/fog-internet-archive being working.

### CODE REVIEW

**Comment by icco** [comment]
This should be ready to go @geemus

**Comment by icco** [comment]
Or maybe not...

**Comment by geemus** [comment]
@icco looks like a couple more lingering weird things around bin still left, if you could fix those also that would be awesome. Thanks!

**Comment by icco** [comment]
Ok @geemus, looks fixed.

**Pull request merged**
