### PR TITLE
vm_clone used regular virtual switches no matter what type of portgroup ...

### PR DESCRIPTION
**Pull request by sofam**
...was named, changed it to look up and handle distributed virtual switches correctly. @nirvdrum

### CODE REVIEW

**Comment by sofam** [comment]
@nirvdrum any comments on this?

**Comment by nirvdrum** [comment]
Sorry.  I forgot about this.  Just to be clear, this is a problem you're seeing even with the merged fix from #3121 applied?

**Comment by sofam** [comment]
@nirvdrum it's actually unrelated (kind of) because the problem lies in the port backing chosen in vm_clone, before my pull request vm_clone would just create a VirtualEthernetCardNetworkBackingInfo port backing, no matter what kind of network was specified, my pull request checks the type of the network chosen, if it's a normal vSwitch it uses VirtualEthernetCardNetworkBackingInfo, and if it's a distributed port group it uses VirtualEthernetCardDistributedVirtualPortBackingInfo.

**Comment by nirvdrum** [comment]
This looks good.  The code formatting doesn't match the new guidelines, but I can clean that up easily enough.  Thanks!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
